#
# Complete cluster setup
# 

---

#
# Set up the apt cache server.
#
- include: playbooks/cacher.yml

#
# The cache server may have been rebooted. Therefore, we need to wait
# until it is up before we do anything else. We wait from the cluster
# hosts (since we might use private IP addresses), rather than from
# localhost. Therefore, we must make sure to exclude the cache machine
# itself, since that one is probably not done rebooting at this point.
#
- name: waiting for caches to come online
  hosts: cluster-hosts:!cache
  gather_facts: False
  tasks:
    - include: tasks/wait_for_cache_servers_create.yml
      when: cache.pkg_cache == "create"
    - include: tasks/wait_for_cache_servers_use.yml
      when: cache.pkg_cache == "use"

- name: create or configure the RDS database, if we are supposed to use it
  hosts: localhost
  gather_facts: False
  tasks:
    - include: tasks/rds_configure.yml
      when: EXT.EC2.rds.use_or_create == "create"  or  EXT.EC2.rds.use_or_create == "use"

#
# Functional setup of cluster servers.
#
- include: playbooks/common.yml
- include: playbooks/backend.yml
- include: playbooks/applayer.yml
- include: playbooks/frontend.yml

