#
# Waiting for the various cache servers, which have been specified for us to use.
#
- name: wait for apt cache server port to be operational (existing cache)
  wait_for: host={{ cache.pkg_cache_existing_ip_addr }} port={{ cache.apt_cache_port }}
- name: wait for PIP cache server port to be operational (existing cache)
  wait_for: host={{ cache.pkg_cache_existing_ip_addr }} port={{ cache.pip_cache_port }}


