#
# Variables for our appserver hosts.
#

---

#
# User
#

myapp_group_name:               "{{ EXT.USERS.deploy_group }}"
myapp_user_name:                "{{ EXT.USERS.deploy_user }}"

#
# For the virtualenv setup
#

install_dir:                     /home/{{ myapp_user_name}}/site
repo_dir:                        "{{ install_dir }}/repo"
requirements_file:               local.txt
pythonpath_dir:                  "{{ repo_dir }}/website"

#
# The application settings
#
appname:                         "{{ EXT.DJANGO.appname }}"

#
# For the Django environment
#

django_env:
  DJANGO_SETTINGS_MODULE: "{{ appname }}.settings.deploy"
  DJANGO_SECRET_KEY:      "{{ EXT.DJANGO.secret }}"
  DJANGO_DB_NAME:         "{{ myapp_db_name }}"
  DJANGO_DB_USER:         "{{ myapp_db_user_name }}"
  DJANGO_DB_PASSWORD:     "{{ myapp_db_user_password }}"
  DJANGO_DB_HOST:         "{{ db_host_addr }}"
  DJANGO_SERVER_DNS:      "{{ EXT.DJANGO.dns }}"
  DJANGO_SERVER_SCHEMA:   "{{ EXT.DJANGO.schema }}"
  DJANGO_SERVER_PORT:     "{{ appserver_port }}"
  DJANGO_TEST_DB:         "test_db_{{ inventory_hostname }}"


